### ISSUE TITLE
Fails to compile with boost 1.55

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/scattered#2]
A change in Boost.Fusion produces a compilation error.
